#!/bin/sh

bspc config border_width 1
bspc config window_gap 15
bspc config top_padding 25
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc desktop -f 1
